#!/usr/bin/env python3

'''
    IGTminer
    Copyright (C) Yongming Chen
    Contact: chen_yongming@126.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
'''

import sys
import subprocess
import os

def PrintVersion() :
	print ("Version:      v1.0.0")

argv_len = len(sys.argv)

DIR=os.path.dirname(sys.argv[0])

if (argv_len) == 1  or sys.argv[1] in ["-h", "-H", "--help"]:
	print ("")
	print ("Program:      IGTminer")
	print ("Description:  A tool for nucleus organelle gene (NOG) map construction")
	PrintVersion()
	print ("")
	print ("Usage:        IGTminer <command> [options]")
	print ("")
	print ("Subcommands include:")
	print ("")
	print ("[ pipeline ]")
	print ("     reannotation          Reannotation of nucleus organelle genes (NOGs)")
	print ("     collinearityNetwork   Pairwise collinear block search and construction of NOG map")
	print ("")
	print ("Author:  Chen,Yongming; chen_yongming@126.com")
	print ("")
else:
	if argv_len == 2 or sys.argv[2] in ["-h", "-H", "--help"]:
		command = ["-h"]
	else:
		command = sys.argv[2:]
	code = sys.argv[1]
	if code == "reannotation":
		subprocess.call([DIR + "/src/01.reannotation.sh"]+ command)
	elif code == "collinearityNetwork":
		subprocess.call([DIR + "/src/02.collinearity.sh"]+ command)

